/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DinnerFavorites extends org.jooq.impl.TableImpl<com.jooqtest.model.tables.records.DinnerFavoritesRecord> {

	private static final long serialVersionUID = 392673740;

	/**
	 * The singleton instance of <code>jooqtest.dinner_favorites</code>
	 */
	public static final com.jooqtest.model.tables.DinnerFavorites DINNER_FAVORITES = new com.jooqtest.model.tables.DinnerFavorites();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jooqtest.model.tables.records.DinnerFavoritesRecord> getRecordType() {
		return com.jooqtest.model.tables.records.DinnerFavoritesRecord.class;
	}

	/**
	 * The column <code>jooqtest.dinner_favorites.foodid</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DinnerFavoritesRecord, java.lang.Long> FOODID = createField("foodid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jooqtest.dinner_favorites.dinner_guest_id</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.DinnerFavoritesRecord, java.lang.Long> DINNER_GUEST_ID = createField("dinner_guest_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * Create a <code>jooqtest.dinner_favorites</code> table reference
	 */
	public DinnerFavorites() {
		this("dinner_favorites", null);
	}

	/**
	 * Create an aliased <code>jooqtest.dinner_favorites</code> table reference
	 */
	public DinnerFavorites(java.lang.String alias) {
		this(alias, com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES);
	}

	private DinnerFavorites(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.DinnerFavoritesRecord> aliased) {
		this(alias, aliased, null);
	}

	private DinnerFavorites(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.DinnerFavoritesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jooqtest.model.Jooqtest.JOOQTEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.jooqtest.model.tables.records.DinnerFavoritesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.jooqtest.model.tables.records.DinnerFavoritesRecord, ?>>asList(com.jooqtest.model.Keys.DINNER_FAVORITES_IBFK_1, com.jooqtest.model.Keys.DINNER_FAVORITES_IBFK_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jooqtest.model.tables.DinnerFavorites as(java.lang.String alias) {
		return new com.jooqtest.model.tables.DinnerFavorites(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jooqtest.model.tables.DinnerFavorites rename(java.lang.String name) {
		return new com.jooqtest.model.tables.DinnerFavorites(name, null);
	}
}
