/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Food extends org.jooq.impl.TableImpl<com.jooqtest.model.tables.records.FoodRecord> {

	private static final long serialVersionUID = -1635198205;

	/**
	 * The singleton instance of <code>jooqtest.food</code>
	 */
	public static final com.jooqtest.model.tables.Food FOOD = new com.jooqtest.model.tables.Food();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.jooqtest.model.tables.records.FoodRecord> getRecordType() {
		return com.jooqtest.model.tables.records.FoodRecord.class;
	}

	/**
	 * The column <code>jooqtest.food.id</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.FoodRecord, java.lang.Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

	/**
	 * The column <code>jooqtest.food.kind</code>.
	 */
	public final org.jooq.TableField<com.jooqtest.model.tables.records.FoodRecord, java.lang.String> KIND = createField("kind", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>jooqtest.food</code> table reference
	 */
	public Food() {
		this("food", null);
	}

	/**
	 * Create an aliased <code>jooqtest.food</code> table reference
	 */
	public Food(java.lang.String alias) {
		this(alias, com.jooqtest.model.tables.Food.FOOD);
	}

	private Food(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.FoodRecord> aliased) {
		this(alias, aliased, null);
	}

	private Food(java.lang.String alias, org.jooq.Table<com.jooqtest.model.tables.records.FoodRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.jooqtest.model.Jooqtest.JOOQTEST, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.jooqtest.model.tables.records.FoodRecord> getPrimaryKey() {
		return com.jooqtest.model.Keys.KEY_FOOD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.jooqtest.model.tables.records.FoodRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.jooqtest.model.tables.records.FoodRecord>>asList(com.jooqtest.model.Keys.KEY_FOOD_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.jooqtest.model.tables.Food as(java.lang.String alias) {
		return new com.jooqtest.model.tables.Food(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.jooqtest.model.tables.Food rename(java.lang.String name) {
		return new com.jooqtest.model.tables.Food(name, null);
	}
}
