/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>jooqtest</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.DinnerGuestsRecord> KEY_DINNER_GUESTS_PRIMARY = UniqueKeys0.KEY_DINNER_GUESTS_PRIMARY;
	public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.FoodRecord> KEY_FOOD_PRIMARY = UniqueKeys0.KEY_FOOD_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DinnerFavoritesRecord, com.jooqtest.model.tables.records.FoodRecord> DINNER_FAVORITES_IBFK_1 = ForeignKeys0.DINNER_FAVORITES_IBFK_1;
	public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DinnerFavoritesRecord, com.jooqtest.model.tables.records.DinnerGuestsRecord> DINNER_FAVORITES_IBFK_2 = ForeignKeys0.DINNER_FAVORITES_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.DinnerGuestsRecord> KEY_DINNER_GUESTS_PRIMARY = createUniqueKey(com.jooqtest.model.tables.DinnerGuests.DINNER_GUESTS, com.jooqtest.model.tables.DinnerGuests.DINNER_GUESTS.ID);
		public static final org.jooq.UniqueKey<com.jooqtest.model.tables.records.FoodRecord> KEY_FOOD_PRIMARY = createUniqueKey(com.jooqtest.model.tables.Food.FOOD, com.jooqtest.model.tables.Food.FOOD.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DinnerFavoritesRecord, com.jooqtest.model.tables.records.FoodRecord> DINNER_FAVORITES_IBFK_1 = createForeignKey(com.jooqtest.model.Keys.KEY_FOOD_PRIMARY, com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES, com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES.FOODID);
		public static final org.jooq.ForeignKey<com.jooqtest.model.tables.records.DinnerFavoritesRecord, com.jooqtest.model.tables.records.DinnerGuestsRecord> DINNER_FAVORITES_IBFK_2 = createForeignKey(com.jooqtest.model.Keys.KEY_DINNER_GUESTS_PRIMARY, com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES, com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES.DINNER_GUEST_ID);
	}
}
