/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in jooqtest
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table jooqtest.dinner_favorites
	 */
	public static final com.jooqtest.model.tables.DinnerFavorites DINNER_FAVORITES = com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES;

	/**
	 * The table jooqtest.dinner_guests
	 */
	public static final com.jooqtest.model.tables.DinnerGuests DINNER_GUESTS = com.jooqtest.model.tables.DinnerGuests.DINNER_GUESTS;

	/**
	 * The table jooqtest.food
	 */
	public static final com.jooqtest.model.tables.Food FOOD = com.jooqtest.model.tables.Food.FOOD;
}
