/**
 * This class is generated by jOOQ
 */
package com.jooqtest.model.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DinnerFavoritesRecord extends org.jooq.impl.TableRecordImpl<com.jooqtest.model.tables.records.DinnerFavoritesRecord> implements org.jooq.Record2<java.lang.Long, java.lang.Long> {

	private static final long serialVersionUID = -944208833;

	/**
	 * Setter for <code>jooqtest.dinner_favorites.foodid</code>.
	 */
	public void setFoodid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>jooqtest.dinner_favorites.foodid</code>.
	 */
	public java.lang.Long getFoodid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>jooqtest.dinner_favorites.dinner_guest_id</code>.
	 */
	public void setDinnerGuestId(java.lang.Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>jooqtest.dinner_favorites.dinner_guest_id</code>.
	 */
	public java.lang.Long getDinnerGuestId() {
		return (java.lang.Long) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Long, java.lang.Long> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES.FOODID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field2() {
		return com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES.DINNER_GUEST_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getFoodid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value2() {
		return getDinnerGuestId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DinnerFavoritesRecord value1(java.lang.Long value) {
		setFoodid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DinnerFavoritesRecord value2(java.lang.Long value) {
		setDinnerGuestId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DinnerFavoritesRecord values(java.lang.Long value1, java.lang.Long value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached DinnerFavoritesRecord
	 */
	public DinnerFavoritesRecord() {
		super(com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES);
	}

	/**
	 * Create a detached, initialised DinnerFavoritesRecord
	 */
	public DinnerFavoritesRecord(java.lang.Long foodid, java.lang.Long dinnerGuestId) {
		super(com.jooqtest.model.tables.DinnerFavorites.DINNER_FAVORITES);

		setValue(0, foodid);
		setValue(1, dinnerGuestId);
	}
}
